# Generated by Django 4.0.4 on 2022-05-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первода')),
                ('recipient', models.IntegerField(verbose_name='ID счета получателя')),
                ('sender', models.IntegerField(verbose_name='ID счета отправителя')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Баланс')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации счета')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последних действий со счетом')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец счета')),
            ],
        ),
    ]
