# Generated by Django 4.0.4 on 2022-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ManyToManyField(to='account.check', verbose_name='ID счетов получателя'),
        ),
    ]
